import LocalizedStrings from 'react-native-localization';

// CommonJS syntax
// let LocalizedStrings = require('react-native-localization');

let strings = new LocalizedStrings({
  "en": {
    greeting: "Hello",
    welcome_message: "Welcome, {0}!",
    item_count: "You have {0} items",
    price_format: "Price: ${0}",
    date_format: "Today is {0}, {1} {2}",
    complex_message: "Hello {0}, you have {1} messages from {2}",
    frog: "frog",
    morning: "morning",
    butterfly: "butterfly",
    mountain: "mountain",
    ocean: "ocean",
    guitar: "guitar",
    rainbow: "rainbow",
    dragon: "dragon",
    crystal: "crystal",
    whisper: "whisper",
    thunder: "thunder",
    moonlight: "moonlight",
    adventure: "adventure",
    harmony: "harmony",
    journey: "journey",
    serenity: "serenity",
    courage: "courage",
    wisdom: "wisdom",
    laughter: "laughter",
    sunset: "sunset",
    forest: "forest",
    river: "river",
    eagle: "eagle",
    dolphin: "dolphin",
    candle: "candle",
    mirror: "mirror",
    bridge: "bridge",
    castle: "castle",
    treasure: "treasure",
    freedom: "freedom"
  },
  "ja": {
    greeting: "こんにちは",
    welcome_message: "{0}さん、ようこそ！",
    item_count: "{0}個のアイテムがあります",
    price_format: "価格: {0}円",
    date_format: "今日は{0}、{1}月{2}日です",
    complex_message: "こんにちは{0}さん、{2}から{1}件のメッセージがあります",
    frog: "カエル",
    morning: "朝",
    butterfly: "蝶",
    mountain: "山",
    ocean: "海",
    guitar: "ギター",
    rainbow: "虹",
    dragon: "竜",
    crystal: "水晶",
    whisper: "ささやき",
    thunder: "雷",
    moonlight: "月光",
    adventure: "冒険",
    harmony: "調和",
    journey: "旅",
    serenity: "静寂",
    courage: "勇気",
    wisdom: "知恵",
    laughter: "笑い",
    sunset: "夕日",
    forest: "森",
    river: "川",
    eagle: "鷲",
    dolphin: "イルカ",
    candle: "ろうそく",
    mirror: "鏡",
    bridge: "橋",
    castle: "城",
    treasure: "宝物",
    freedom: "自由"
  },
  "ar": {
    greeting: "مرحبا",
    frog: "ضفدع",
    morning: "صباح",
    butterfly: "فراشة",
    mountain: "جبل",
    ocean: "محيط",
    guitar: "جيتار",
    rainbow: "قوس قزح",
    dragon: "تنين",
    crystal: "بلورة",
    whisper: "همس",
    thunder: "رعد",
    moonlight: "ضوء القمر",
    adventure: "مغامرة",
    harmony: "تناغم",
    journey: "رحلة",
    serenity: "هدوء",
    courage: "شجاعة",
    wisdom: "حكمة",
    laughter: "ضحك",
    sunset: "غروب الشمس",
    forest: "غابة",
    river: "نهر",
    eagle: "نسر",
    dolphin: "دلفين",
    candle: "شمعة",
    mirror: "مرآة",
    bridge: "جسر",
    castle: "قلعة",
    treasure: "كنز",
    freedom: "حرية"
  },
  "de": {
    greeting: "Hallo",
    frog: "Frosch",
    morning: "Morgen",
    butterfly: "Schmetterling",
    mountain: "Berg",
    ocean: "Ozean",
    guitar: "Gitarre",
    rainbow: "Regenbogen",
    dragon: "Drache",
    crystal: "Kristall",
    whisper: "Flüstern",
    thunder: "Donner",
    moonlight: "Mondlicht",
    adventure: "Abenteuer",
    harmony: "Harmonie",
    journey: "Reise",
    serenity: "Gelassenheit",
    courage: "Mut",
    wisdom: "Weisheit",
    laughter: "Lachen",
    sunset: "Sonnenuntergang",
    forest: "Wald",
    river: "Fluss",
    eagle: "Adler",
    dolphin: "Delfin",
    candle: "Kerze",
    mirror: "Spiegel",
    bridge: "Brücke",
    castle: "Schloss",
    treasure: "Schatz",
    freedom: "Freiheit"
  }
});

export default strings;

// Usage example:
// import strings from './LocalizedStrings';
// console.log(strings.greeting);
// console.log(strings.formatString(strings.welcome_message, ['John']));